import { useCallback, useEffect, useSyncExternalStore } from 'react'

export type Lang = 'zh' | 'en'

const STORAGE_KEY = 'yohaku-design-lang'
const URL_PARAM = 'lang'
const CHANGE_EVENT = 'yohaku-lang-change'

function readLang(): Lang {
  if (typeof window === 'undefined') return 'zh'
  const fromUrl = new URL(window.location.href).searchParams.get(URL_PARAM)
  if (fromUrl === 'zh' || fromUrl === 'en') return fromUrl
  const stored = window.localStorage.getItem(STORAGE_KEY)
  if (stored === 'zh' || stored === 'en') return stored
  return navigator.language.startsWith('zh') ? 'zh' : 'en'
}

function subscribe(cb: () => void) {
  window.addEventListener('popstate', cb)
  window.addEventListener(CHANGE_EVENT, cb)
  return () => {
    window.removeEventListener('popstate', cb)
    window.removeEventListener(CHANGE_EVENT, cb)
  }
}

export function useLang() {
  const lang = useSyncExternalStore(
    subscribe,
    readLang,
    () => 'zh' as Lang,
  )

  useEffect(() => {
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en'
  }, [lang])

  const setLang = useCallback((next: Lang) => {
    const url = new URL(window.location.href)
    url.searchParams.set(URL_PARAM, next)
    window.history.replaceState(null, '', url)
    window.localStorage.setItem(STORAGE_KEY, next)
    window.dispatchEvent(new Event(CHANGE_EVENT))
  }, [])

  return { lang, setLang }
}

type Dict = Record<Lang, string>

export const dict = {
  // Hero
  heroEyebrow: { zh: '设计系统 · v0.1', en: 'Design System · v0.1' },
  heroTitle: { zh: 'Yohaku', en: 'Yohaku' },
  heroSubtitle: { zh: '余白', en: 'Yohaku' },
  heroTagline: {
    zh: '一种主色，三档中性灰，剩下都是留白。Yohaku 是一套为书写而设计的系统——网页、长文、信件、报告，凡是承载文字的地方都能用。',
    en: 'One accent, three neutral tiers, the rest is whitespace. Yohaku is a design system for written content — web, long-form, letters, reports, anywhere words live.',
  },
  heroTokenAccent: { zh: '主色', en: 'Accent' },
  heroTokenNeutral: { zh: '中性', en: 'Neutral' },
  heroTokenSerif: { zh: '衬线', en: 'Serif' },
  heroTokenMono: { zh: '等宽', en: 'Mono' },

  // 00 Output samples
  outputNum: { zh: '00 · 出样', en: '00 · See it' },
  outputTitle: { zh: '输出样本', en: 'Output Samples' },
  outputLede: {
    zh: '用 Yohaku 做出来的三类真实页面：长文、简历、一页报告。每一份都是完整可独立打开的 HTML，并附带浏览器打印生成的 PDF。点一下封面在新标签页打开网页版，下方链接下载 PDF 版。',
    en: 'Three kinds of real pages Yohaku produces: long-form post, resume, one-page report. Each is a complete standalone HTML, with a PDF generated by browser print-to-PDF. Click the cover to open the web version in a new tab, or use the link below to download the PDF.',
  },

  // 01 Manifesto
  manifestoNum: { zh: '01 · 主张', en: '01 · Manifesto' },
  manifestoTitle: { zh: '设计原则', en: 'Design Principles' },
  manifestoLede: {
    zh: '现在屏幕和纸面上的视觉信息已经太多。Yohaku 选择做减法——只用一种主色（梅红），三档暖灰，去掉硬阴影和花哨色阶。目的是让书写本身能被看清，让内容可读、可信、能长期留存。',
    en: 'In a saturated visual world, Yohaku is built by subtraction. One ume accent, three tiers of warm gray, no hard shadows, no flashy palettes — built for readable, trustworthy written content.',
  },

  // 02 Color
  colorNum: { zh: '02 · 颜色', en: '02 · Color' },
  colorTitle: { zh: '克制的色彩', en: 'Restrained Palette' },
  colorLede: {
    zh: '一种主色 + 纯中性灰 + 零冷色。主色在任何一个界面里都不超过 5%，超过这个比例就显得吵闹。',
    en: 'One accent + pure neutrals + zero cool tones. Accent never exceeds 5% of any surface — beyond that is noise.',
  },
  colorNeutralHead: { zh: '中性灰 · 三档', en: 'Neutral · Three Tiers' },
  colorAccentHead: { zh: '主色 · 梅红', en: 'Accent · Single Ume' },
  colorSemanticHead: { zh: '语义色', en: 'Semantic' },

  // 03 Typography
  typeNum: { zh: '03 · 字体', en: '03 · Typography' },
  typeTitle: { zh: '三类字体', en: 'Three Font Roles' },
  typeLede: {
    zh: '衬线字体承担层级，无衬线字体承担功能，等宽字体承担代码。每一族都自带中文回退链，中文不需要再做妥协。',
    en: 'Serif carries hierarchy, sans carries function, mono carries code. Every stack ships with a mandatory CJK fallback chain.',
  },
  typeScaleHead: { zh: '尺度', en: 'Scale' },

  // 04 Spacing
  spaceNum: { zh: '04 · 间距', en: '04 · Spacing' },
  spaceTitle: { zh: '节奏与形态', en: 'Rhythm & Form' },
  spaceLede: {
    zh: '间距按 Tailwind 默认的 4px 一档。圆角最大用到 rounded-2xl（16px），再大就只是装饰了。',
    en: 'Tailwind default 4px steps. Hero radius caps at rounded-2xl (16px); beyond that reads decorative.',
  },
  radiusHead: { zh: '圆角', en: 'Radius' },
  shadowHead: { zh: '深度 · 描边和淡阴影', en: 'Depth · Ring & Whisper' },

  // 05 Components
  compNum: { zh: '05 · 原子组件', en: '05 · Atoms' },
  compTitle: { zh: '原子组件', en: 'Atomic Modules' },
  compLede: {
    zh: '一组数量不多但定下来的组件，每一件解决一个具体问题。',
    en: 'A small, fixed component set — each piece solves a specific document problem.',
  },

  // 06 Snippets
  snippetNum: { zh: '06 · 段落', en: '06 · Snippets' },
  snippetTitle: { zh: '段落样例', en: 'Section Snippets' },
  snippetLede: {
    zh: '五个可复用的段落：评论流、表单、代码块、弹框、底部抽屉。每一个都对齐 apps/web 里实际使用的样式和 token。',
    en: 'Five reusable section snippets: comment-thread, form, code-block, modal, sheet. Each mirrors the actual styling and tokens used in apps/web.',
  },

  // 07 Anti-patterns
  antiNum: { zh: '07 · 注意', en: '07 · Anti-Patterns' },
  antiTitle: { zh: '需要避免的做法', en: 'What to Avoid' },
  antiLede: {
    zh: 'verify 脚本会自动挡掉最严重的几种。下面列的是这些规则背后的原因。',
    en: 'The verify script blocks the worst mechanically. This list is the reasoning behind those checks.',
  },
  antiDontLabel: { zh: '别这样', en: "Don't" },
  antiDoLabel: { zh: '该这样', en: 'Do' },

  // 08 Decision
  decideNum: { zh: '08 · 速查', en: '08 · Decision Lookup' },
  decideTitle: { zh: '快速决策表', en: 'Quick Reference' },
  decideLede: {
    zh: '不知道该用哪个 token 时，先查这张表。表里没有的，回到基本原则。',
    en: 'When in doubt about what token to use, consult this table first. Beyond that, return to first principles.',
  },

  // 09 Background
  bgNum: { zh: '09 · 由来', en: '09 · Origin' },
  bgTitle: { zh: '它从哪来', en: 'Design Origins' },

  // Footer
  footerLine: {
    zh: '衬线字体承担权威感，无衬线字体承担功能，暖灰承担节奏，梅红承担焦点。',
    en: 'Serif carries authority, sans carries function, neutrals carry rhythm, ume carries focus.',
  },
} satisfies Record<string, Dict>

export type DictKey = keyof typeof dict

export function t(key: DictKey, lang: Lang): string {
  return dict[key][lang]
}
